name: Rust

on:
  push:
    branches:
      - master
      - "feature/*"
  pull_request: {}

jobs:
  macos_build:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        feature: ["", "serialize"]

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features=${{ matrix.feature }} --no-default-features

  macos_test:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        feature: ["", "serialize"]

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features=${{ matrix.feature }} --no-default-features


  linux_build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        feature: ["", "serialize"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features=${{ matrix.feature }} --no-default-features

  linux_test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        feature: ["", "serialize"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features=${{ matrix.feature }} --no-default-features

  check-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        command: fmt
        args: -- --check

  clippy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features